/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/console/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_console_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_console_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_console_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_console_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_console_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filters */
        get: operations["filters_api_console_v1_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_console_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/jobs/{public_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_console_v1_jobs__public_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/jobs/{public_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_console_v1_jobs__public_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_api_console_v1_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/reviews/{public_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review */
        get: operations["get_review_api_console_v1_reviews__public_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentResultModel */
        AgentResultModel: {
            /** Name */
            name: string;
            /** Score */
            score: number | string | boolean | null;
            /** Criteria */
            criteria: {
                [key: string]: unknown;
            }[];
            /** Issues */
            issues: {
                [key: string]: unknown;
            }[];
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            }[];
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /**
             * Current Password
             * @default
             */
            current_password: string;
            /**
             * New Password
             * @default
             */
            new_password: string;
        };
        /** CostEstimateModel */
        CostEstimateModel: {
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Estimated Usd */
            estimated_usd: number | null;
            /** Pricing Version */
            pricing_version: number;
            /** Effective At */
            effective_at: string;
            /** Currency */
            currency: string;
            /** Source */
            source: string;
            /** Unknown Models */
            unknown_models: string[];
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Date From */
            date_from: string;
            /** Date To */
            date_to: string;
            /** Queue Counts */
            queue_counts: {
                [key: string]: number;
            };
            /** Total Reviews */
            total_reviews: number;
            /** Decision Counts */
            decision_counts: {
                [key: string]: number;
            };
            /** Duration P50 Ms */
            duration_p50_ms: number | null;
            /** Duration P95 Ms */
            duration_p95_ms: number | null;
            cost_estimate: components["schemas"]["CostEstimateModel"];
            /** Writeback Counts */
            writeback_counts: {
                [key: string]: number;
            };
            /** Writeback Success Rate */
            writeback_success_rate: number | null;
            /** Worker Status */
            worker_status: string;
            /** Connector Status */
            connector_status: string;
            /** Worker Running */
            worker_running: number;
            /** Worker Stale */
            worker_stale: number;
            /** Worker Last Seen At */
            worker_last_seen_at: string | null;
        };
        /**
         * FiltersResponse
         * @description Gia tri hop le cho moi bo loc, lay tu server.
         *
         *     Ton tai de frontend khong hard-code danh sach nao. Mot brief tung ghi
         *     trang thai job la `succeeded` trong khi that su la `done`, va khong phep
         *     kiem nao bat duoc vi gia tri hop le chua bao gio nam trong hop dong.
         */
        FiltersResponse: {
            /** Sites */
            sites: components["schemas"]["SiteOptionModel"][];
            /** Job Sources */
            job_sources: string[];
            /** Job Statuses */
            job_statuses: string[];
            /** Review Decisions */
            review_decisions: string[];
            /** Writeback Statuses */
            writeback_statuses: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobDetailModel */
        JobDetailModel: {
            /** Public Id */
            public_id: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Site Id */
            site_id: string;
            /** Site Slug */
            site_slug: string;
            /** Site Name */
            site_name: string;
            /** Profile Id */
            profile_id: string;
            /** Policy Version */
            policy_version: string;
            /** External Content Id */
            external_content_id: string;
            /** External Revision Id */
            external_revision_id: string | null;
            /** Content Type */
            content_type: string;
            /** Langcode */
            langcode: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /** Source */
            source: string;
            /** Correlation Id */
            correlation_id: string;
            /** Supersedes Job Public Id */
            supersedes_job_public_id: string | null;
            /** Last Error */
            last_error: string | null;
            /** Run Public Id */
            run_public_id: string | null;
            /** Writeback Status */
            writeback_status: string | null;
            /** Run Scored At */
            run_scored_at: string | null;
            /** Saved Result Available */
            saved_result_available: boolean;
        };
        /** JobListItemModel */
        JobListItemModel: {
            /** Public Id */
            public_id: string;
            /** Created At */
            created_at: string;
            /** Site Id */
            site_id: string;
            /** Site Slug */
            site_slug: string;
            /** External Content Id */
            external_content_id: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /** Source */
            source: string;
            /** Policy Version */
            policy_version: string;
        };
        /** JobPage */
        JobPage: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
            /** Items */
            items: components["schemas"]["JobListItemModel"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Password
             * @default
             */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Must Change Password */
            must_change_password: boolean;
            /** Csrf Token */
            csrf_token: string;
        };
        /** RetryRequest */
        RetryRequest: {
            /**
             * Confirm Cost
             * @default false
             */
            confirm_cost: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** ReviewDetailModel */
        ReviewDetailModel: {
            /** Public Id */
            public_id: string;
            /** Scored At */
            scored_at: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Decision */
            decision: string | null;
            /** Final Score */
            final_score: number | null;
            /** Missing Agents */
            missing_agents: string[];
            /** Veto Reason */
            veto_reason: string | null;
            /** Note */
            note: string | null;
            /** Agents */
            agents: components["schemas"]["AgentResultModel"][];
            /** Config Meta */
            config_meta: {
                [key: string]: unknown;
            } | unknown[] | string | number | boolean | null;
            cost_estimate: components["schemas"]["CostEstimateModel"];
            /** Usage Available */
            usage_available: boolean;
            /** Model */
            model: string;
            /** Writeback Status */
            writeback_status: string;
            /** Writeback Error */
            writeback_error: string | null;
            /** Site Id */
            site_id: string;
            /** Site Slug */
            site_slug: string;
            /** Site Name */
            site_name: string;
            /** Profile Id */
            profile_id: string;
            /** Profile Code */
            profile_code: string;
            /** Policy Version */
            policy_version: string;
            /** External Content Id */
            external_content_id: string;
            /** External Revision Id */
            external_revision_id: string | null;
            /** Content Type */
            content_type: string;
            /** Langcode */
            langcode: string;
            /** Correlation Id */
            correlation_id: string;
            /** Is Fixture */
            is_fixture: boolean;
            /** Drupal Url */
            drupal_url: string | null;
        };
        /** ReviewListItemModel */
        ReviewListItemModel: {
            /** Public Id */
            public_id: string;
            /** Scored At */
            scored_at: string;
            /** Site Id */
            site_id: string;
            /** Site Slug */
            site_slug: string;
            /** External Content Id */
            external_content_id: string;
            /** Decision */
            decision: string | null;
            /** Final Score */
            final_score: number | null;
            /** Profile Code */
            profile_code: string;
            /** Policy Version */
            policy_version: string;
            /** Model */
            model: string;
            /** Is Fixture */
            is_fixture: boolean;
        };
        /** ReviewPage */
        ReviewPage: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
            /** Items */
            items: components["schemas"]["ReviewListItemModel"][];
        };
        /** SiteOptionModel */
        SiteOptionModel: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Active */
            active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_console_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_console_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    logout_api_console_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_password_api_console_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_console_v1_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    filters_api_console_v1_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiltersResponse"];
                };
            };
        };
    };
    list_jobs_api_console_v1_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
        };
    };
    get_job_api_console_v1_jobs__public_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_console_v1_jobs__public_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_api_console_v1_reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPage"];
                };
            };
        };
    };
    get_review_api_console_v1_reviews__public_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDetailModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
