/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/console/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_api_console_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_console_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_console_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_console_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_console_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Connection */
        get: operations["get_connection_api_console_v1_connection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/connection/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Connection */
        post: operations["test_connection_api_console_v1_connection_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/connection/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Intake */
        post: operations["pause_intake_api_console_v1_connection_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/connection/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Intake */
        post: operations["resume_intake_api_console_v1_connection_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_console_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filters */
        get: operations["filters_api_console_v1_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_console_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/jobs/{public_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_console_v1_jobs__public_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/jobs/{public_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_console_v1_jobs__public_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/config-kb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config Kb */
        get: operations["config_kb_api_console_v1_config_kb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluation List */
        get: operations["evaluation_list_api_console_v1_evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/evaluation/evidence/{experiment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evaluation Evidence
         * @description Tra FILE THO, khong phai JSON.
         *
         *     Giu nguyen hai header cua admin cu. `nosniff` la thu ngan trinh duyet doan
         *     kieu mot file .txt thanh HTML roi chay script trong do; bo di la mo mot
         *     duong XSS qua noi dung file bang chung.
         */
        get: operations["evaluation_evidence_api_console_v1_evaluation_evidence__experiment__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_api_console_v1_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/reviews/{public_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review */
        get: operations["get_review_api_console_v1_reviews__public_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_console_v1_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_console_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Role */
        post: operations["change_role_api_console_v1_users__user_id__role_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/users/{user_id}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock User */
        post: operations["lock_user_api_console_v1_users__user_id__lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/users/{user_id}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlock User */
        post: operations["unlock_user_api_console_v1_users__user_id__unlock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/v1/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_console_v1_users__user_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentResultModel */
        AgentResultModel: {
            /** Name */
            name: string;
            /** Score */
            score: number | string | boolean | null;
            /** Criteria */
            criteria: {
                [key: string]: unknown;
            }[];
            /** Issues */
            issues: {
                [key: string]: unknown;
            }[];
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            }[];
        };
        /** AuditEventModel */
        AuditEventModel: {
            /** Id */
            id: number;
            /** Actor User Id */
            actor_user_id: string | null;
            /** Actor Username */
            actor_username: string;
            /** Action */
            action: string;
            /** Target Type */
            target_type: string;
            /** Target Id */
            target_id: string | null;
            /** Outcome */
            outcome: string;
            /** Metadata Text */
            metadata_text: string;
            /** Created At */
            created_at: string;
        };
        /** AuditPage */
        AuditPage: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
            /** Items */
            items: components["schemas"]["AuditEventModel"][];
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /**
             * Current Password
             * @default
             */
            current_password: string;
            /**
             * New Password
             * @default
             */
            new_password: string;
        };
        /** ChangeRoleRequest */
        ChangeRoleRequest: {
            /**
             * Role
             * @default
             */
            role: string;
        };
        /** ConfigKbResponse */
        ConfigKbResponse: {
            /** Policy Files */
            policy_files: components["schemas"]["PolicyFileModel"][];
            /** Profile Assignments */
            profile_assignments: components["schemas"]["ProfileAssignmentModel"][];
            /** Kb Summary */
            kb_summary: components["schemas"]["KBSummaryModel"][];
        };
        /** ConnectionModel */
        ConnectionModel: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Base Url */
            base_url: string;
            /** Secret Ref */
            secret_ref: string;
            /** Active */
            active: boolean;
            /** Intake Paused */
            intake_paused: boolean;
            /** Profile Code */
            profile_code: string | null;
            /** Policy Version */
            policy_version: string | null;
            /** Token Prefixes */
            token_prefixes: string[];
            /** Last Health Status */
            last_health_status: string | null;
            /** Last Health Checked At */
            last_health_checked_at: string | null;
            /** Last Health Error */
            last_health_error: string | null;
        };
        /** CostEstimateModel */
        CostEstimateModel: {
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Estimated Usd */
            estimated_usd: number | null;
            /** Pricing Version */
            pricing_version: number;
            /** Effective At */
            effective_at: string;
            /** Currency */
            currency: string;
            /** Source */
            source: string;
            /** Unknown Models */
            unknown_models: string[];
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Role
             * @default
             */
            role: string;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Date From */
            date_from: string;
            /** Date To */
            date_to: string;
            /** Queue Counts */
            queue_counts: {
                [key: string]: number;
            };
            /** Total Reviews */
            total_reviews: number;
            /** Decision Counts */
            decision_counts: {
                [key: string]: number;
            };
            /** Duration P50 Ms */
            duration_p50_ms: number | null;
            /** Duration P95 Ms */
            duration_p95_ms: number | null;
            cost_estimate: components["schemas"]["CostEstimateModel"];
            /** Writeback Counts */
            writeback_counts: {
                [key: string]: number;
            };
            /** Writeback Success Rate */
            writeback_success_rate: number | null;
            /** Worker Status */
            worker_status: string;
            /** Connector Status */
            connector_status: string;
            /** Worker Running */
            worker_running: number;
            /** Worker Stale */
            worker_stale: number;
            /** Worker Last Seen At */
            worker_last_seen_at: string | null;
        };
        /** EvaluationResponse */
        EvaluationResponse: {
            /** Experiments */
            experiments: components["schemas"]["ExperimentModel"][];
        };
        /** ExperimentModel */
        ExperimentModel: {
            /** Experiment */
            experiment: string;
            /** Status */
            status: string;
            /** Score Path Snapshot */
            score_path_snapshot: string | null;
            /** Head Commit */
            head_commit: string | null;
            /** Prompt Version */
            prompt_version: string | null;
            /** Model */
            model: string | null;
            /** Run At */
            run_at: string | null;
            /** Evidence Path */
            evidence_path: string | null;
            /** Metadata Complete */
            metadata_complete: boolean;
            /** Summary */
            summary: string;
            /** Has Evidence */
            has_evidence: boolean;
            /** Provenance Warning */
            provenance_warning: string | null;
        };
        /**
         * FiltersResponse
         * @description Gia tri hop le cho moi bo loc, lay tu server.
         *
         *     Ton tai de frontend khong hard-code danh sach nao. Mot brief tung ghi
         *     trang thai job la `succeeded` trong khi that su la `done`, va khong phep
         *     kiem nao bat duoc vi gia tri hop le chua bao gio nam trong hop dong.
         */
        FiltersResponse: {
            /** Sites */
            sites: components["schemas"]["SiteOptionModel"][];
            /** Job Sources */
            job_sources: string[];
            /** Job Statuses */
            job_statuses: string[];
            /** Roles */
            roles: string[];
            /** Review Decisions */
            review_decisions: string[];
            /** Writeback Statuses */
            writeback_statuses: string[];
            /** Audit Actions */
            audit_actions: string[];
            /** Audit Outcomes */
            audit_outcomes: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobDetailModel */
        JobDetailModel: {
            /** Public Id */
            public_id: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Site Id */
            site_id: string;
            /** Site Slug */
            site_slug: string;
            /** Site Name */
            site_name: string;
            /** Profile Id */
            profile_id: string;
            /** Policy Version */
            policy_version: string;
            /** External Content Id */
            external_content_id: string;
            /** External Revision Id */
            external_revision_id: string | null;
            /** Content Type */
            content_type: string;
            /** Langcode */
            langcode: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /** Source */
            source: string;
            /** Correlation Id */
            correlation_id: string;
            /** Supersedes Job Public Id */
            supersedes_job_public_id: string | null;
            /** Last Error */
            last_error: string | null;
            /** Run Public Id */
            run_public_id: string | null;
            /** Writeback Status */
            writeback_status: string | null;
            /** Run Scored At */
            run_scored_at: string | null;
            /** Saved Result Available */
            saved_result_available: boolean;
        };
        /** JobListItemModel */
        JobListItemModel: {
            /** Public Id */
            public_id: string;
            /** Created At */
            created_at: string;
            /** Site Id */
            site_id: string;
            /** Site Slug */
            site_slug: string;
            /** External Content Id */
            external_content_id: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /** Source */
            source: string;
            /** Policy Version */
            policy_version: string;
        };
        /** JobPage */
        JobPage: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
            /** Items */
            items: components["schemas"]["JobListItemModel"][];
        };
        /** KBSummaryModel */
        KBSummaryModel: {
            /** Collection */
            collection: string;
            /** Content Type */
            content_type: string;
            /** Langcode */
            langcode: string;
            /** Chunk Count */
            chunk_count: number;
            /** Metadata Excerpt */
            metadata_excerpt: string;
            /** Embedding Model */
            embedding_model: string | null;
            /** Embedding Dimension */
            embedding_dimension: number | null;
        };
        /**
         * LabelValueModel
         * @description Cap nhan-gia tri co THU TU.
         *
         *     Nguon la tuple[tuple[str, str], ...] nen thu tu co y nghia. Doi sang dict
         *     se mat thu tu do va co the nuot khoa trung.
         */
        LabelValueModel: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Password
             * @default
             */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Must Change Password */
            must_change_password: boolean;
            /** Csrf Token */
            csrf_token: string;
        };
        /** PolicyFileModel */
        PolicyFileModel: {
            /** Label */
            label: string;
            /** Relative Path */
            relative_path: string;
            /** Sha256 */
            sha256: string;
            /** Modified At */
            modified_at: string;
            /** Metadata */
            metadata: components["schemas"]["LabelValueModel"][];
            /** Error */
            error: string | null;
        };
        /** ProfileAssignmentModel */
        ProfileAssignmentModel: {
            /** Site Slug */
            site_slug: string;
            /** Site Name */
            site_name: string;
            /** Connector Type */
            connector_type: string;
            /** Site Active */
            site_active: boolean;
            /** Intake Paused */
            intake_paused: boolean;
            /** Profile Code */
            profile_code: string;
            /** Market Code */
            market_code: string;
            /** Language Code */
            language_code: string;
            /** Content Type */
            content_type: string;
            /** Profile Status */
            profile_status: string;
            /** Policy Version */
            policy_version: string;
            /** Policy Metadata */
            policy_metadata: components["schemas"]["LabelValueModel"][];
        };
        /** ReasonRequest */
        ReasonRequest: {
            /** Reason */
            reason?: string | null;
        };
        /** RetryRequest */
        RetryRequest: {
            /**
             * Confirm Cost
             * @default false
             */
            confirm_cost: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** ReviewDetailModel */
        ReviewDetailModel: {
            /** Public Id */
            public_id: string;
            /** Scored At */
            scored_at: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Decision */
            decision: string | null;
            /** Final Score */
            final_score: number | null;
            /** Missing Agents */
            missing_agents: string[];
            /** Veto Reason */
            veto_reason: string | null;
            /** Note */
            note: string | null;
            /** Agents */
            agents: components["schemas"]["AgentResultModel"][];
            /** Config Meta */
            config_meta: {
                [key: string]: unknown;
            } | unknown[] | string | number | boolean | null;
            cost_estimate: components["schemas"]["CostEstimateModel"];
            /** Usage Available */
            usage_available: boolean;
            /** Model */
            model: string;
            /** Writeback Status */
            writeback_status: string;
            /** Writeback Error */
            writeback_error: string | null;
            /** Site Id */
            site_id: string;
            /** Site Slug */
            site_slug: string;
            /** Site Name */
            site_name: string;
            /** Profile Id */
            profile_id: string;
            /** Profile Code */
            profile_code: string;
            /** Policy Version */
            policy_version: string;
            /** External Content Id */
            external_content_id: string;
            /** External Revision Id */
            external_revision_id: string | null;
            /** Content Type */
            content_type: string;
            /** Langcode */
            langcode: string;
            /** Correlation Id */
            correlation_id: string;
            /** Is Fixture */
            is_fixture: boolean;
            /** Drupal Url */
            drupal_url: string | null;
        };
        /** ReviewListItemModel */
        ReviewListItemModel: {
            /** Public Id */
            public_id: string;
            /** Scored At */
            scored_at: string;
            /** Site Id */
            site_id: string;
            /** Site Slug */
            site_slug: string;
            /** External Content Id */
            external_content_id: string;
            /** Decision */
            decision: string | null;
            /** Final Score */
            final_score: number | null;
            /** Profile Code */
            profile_code: string;
            /** Policy Version */
            policy_version: string;
            /** Model */
            model: string;
            /** Is Fixture */
            is_fixture: boolean;
        };
        /** ReviewPage */
        ReviewPage: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
            /** Items */
            items: components["schemas"]["ReviewListItemModel"][];
        };
        /** SiteOptionModel */
        SiteOptionModel: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Active */
            active: boolean;
        };
        /**
         * TemporaryPasswordResponse
         * @description Tra ve DUY NHAT mot lan, ngay sau khi tao hoac dat lai mat khau.
         *
         *     Endpoint tra kieu nay phai dat Cache-Control: no-store. Mat khau con dung
         *     duoc ma nam trong bo nho dem cua proxy hay trinh duyet la mot ban sao
         *     khong ai kiem soat va khong ai thu hoi duoc.
         */
        TemporaryPasswordResponse: {
            user: components["schemas"]["UserModel"];
            /** Temporary Password */
            temporary_password: string;
        };
        /** TestConnectionResponse */
        TestConnectionResponse: {
            /** Ok */
            ok: boolean;
            /** Error Code */
            error_code: string | null;
            connection: components["schemas"]["ConnectionModel"];
        };
        /**
         * UserModel
         * @description Mot tai khoan quan tri.
         *
         *     KHONG co truong nao lien quan toi mat khau. `password_hash` nam ngay canh
         *     cac cot nay trong bang, nen moi lan them truong phai kiem lai: mot bam
         *     Argon2 lot ra ngoai la mot muc tieu be khoa ngoai tuyen.
         */
        UserModel: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Active */
            active: boolean;
            /** Must Change Password */
            must_change_password: boolean;
            /** Last Login At */
            last_login_at: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** UserPage */
        UserPage: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
            /** Items */
            items: components["schemas"]["UserModel"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_api_console_v1_audit_get: {
        parameters: {
            query?: {
                /** @description xem GET /filters */
                action?: string | null;
                /** @description success|denied|failed */
                outcome?: string | null;
                /** @description khop mot phan ten dang nhap */
                actor?: string | null;
                /** @description YYYY-MM-DD */
                from?: string | null;
                /** @description phai di cung `from` */
                to?: string | null;
                /** @description mac dinh 1 */
                page?: string | null;
                /** @description mac dinh 25, toi da 100 */
                page_size?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_console_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_console_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    logout_api_console_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_password_api_console_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connection_api_console_v1_connection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionModel"];
                };
            };
        };
    };
    test_connection_api_console_v1_connection_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionResponse"];
                };
            };
        };
    };
    pause_intake_api_console_v1_connection_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_intake_api_console_v1_connection_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_console_v1_dashboard_get: {
        parameters: {
            query?: {
                /** @description YYYY-MM-DD */
                from?: string | null;
                /** @description phai di cung `from` */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    filters_api_console_v1_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiltersResponse"];
                };
            };
        };
    };
    list_jobs_api_console_v1_jobs_get: {
        parameters: {
            query?: {
                /** @description queued|running|failed|done|superseded */
                status?: string | null;
                /** @description slug cua site, khop chinh xac */
                site?: string | null;
                /** @description khop chinh xac, xem GET /filters */
                source?: string | null;
                /** @description khop mot phan chuoi */
                external_id?: string | null;
                /** @description YYYY-MM-DD */
                from?: string | null;
                /** @description phai di cung `from` */
                to?: string | null;
                /** @description mac dinh 1 */
                page?: string | null;
                /** @description mac dinh 25, toi da 100 */
                page_size?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_console_v1_jobs__public_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_console_v1_jobs__public_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_kb_api_console_v1_config_kb_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigKbResponse"];
                };
            };
        };
    };
    evaluation_list_api_console_v1_evaluation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResponse"];
                };
            };
        };
    };
    evaluation_evidence_api_console_v1_evaluation_evidence__experiment__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_api_console_v1_reviews_get: {
        parameters: {
            query?: {
                /** @description publish|needs_revision|rejected|unknown */
                decision?: string | null;
                /** @description slug cua site, khop chinh xac */
                site?: string | null;
                /** @description khop mot phan chuoi */
                external_id?: string | null;
                /** @description YYYY-MM-DD */
                from?: string | null;
                /** @description phai di cung `from` */
                to?: string | null;
                /** @description mac dinh 1 */
                page?: string | null;
                /** @description mac dinh 25, toi da 100 */
                page_size?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_api_console_v1_reviews__public_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDetailModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_console_v1_users_get: {
        parameters: {
            query?: {
                /** @description mac dinh 1 */
                page?: string | null;
                /** @description mac dinh 25, toi da 100 */
                page_size?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_console_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemporaryPasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_role_api_console_v1_users__user_id__role_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_user_api_console_v1_users__user_id__lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlock_user_api_console_v1_users__user_id__unlock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_console_v1_users__user_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemporaryPasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
